apiVersion: v1
kind: Service
metadata:
  name: landing-page-service
  labels:
    app: landing-page
spec:
  selector:
    app: landing-page
    tier: web
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
  loadBalancerIP: "35.188.106.167"
